apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cluster-agent
  labels:
    app: k8s-cluster-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list"]
  
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get"]
  
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"] 