apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-cluster-agent
  namespace: k8s-cluster-agent
  labels:
    app: k8s-cluster-agent
spec:
  selector:
    matchLabels:
      app: k8s-cluster-agent
  template:
    metadata:
      labels:
        app: k8s-cluster-agent
    spec:
      serviceAccountName: k8s-cluster-agent
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      # Tolerations to ensure the agent can run on all nodes including master nodes
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: agent
        image: ghcr.io/sumandas0/k8s-cluster-agent:main-131dc4e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: PORT
          value: "8080"
        # Add node name as environment variable for better logging
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL 