apiVersion: v1
kind: Service
metadata:
  name: k8s-cluster-agent
  namespace: k8s-cluster-agent
  labels:
    app: k8s-cluster-agent
spec:
  type: ClusterIP
  selector:
    app: k8s-cluster-agent
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP 