apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-cluster-agent
  namespace: k8s-cluster-agent
spec:
  template:
    spec:
      containers:
      - name: agent
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: LOG_FORMAT
          value: "text"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi 