apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cluster-agent
  namespace: k8s-cluster-agent
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: agent
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: LOG_FORMAT
          value: "text"
        resources:
          requests:
            cpu: 100m
            memory: 320Mi
          limits:
            cpu: 500m
            memory: 640Mi 